include Makefile.inc

SOURCES_SERVER=$(SOURCES_FOLDER)/server.c 
SOURCES_CHALLENGES=$(SOURCES_FOLDER)/challenges.c 
SOURCES_CLIENT=$(SOURCES_FOLDER)/client.c  

SOURCES_FOLDER=src
OUTPUT_FOLDER=bin
INCLUDE_FOLDER=$(SOURCES_FOLDER)/include

OUTPUT_SERVER=$(OUTPUT_FOLDER)/server
OUTPUT_CLIENT=$(OUTPUT_FOLDER)/client

all: $(OUTPUT_SERVER) $(OUTPUT_CLIENT) 

$(OUTPUT_SERVER): $(SOURCES_SERVER) $(SOURCES_CHALLENGES)
	$(GCC) $(GCCFLAGS) -I$(INCLUDE_FOLDER) $^ -o $@;
	@echo too_easy >> $(OUTPUT_SERVER);

$(OUTPUT_CLIENT): $(SOURCES_CLIENT) 
	$(GCC) $(GCCFLAGS) -I$(INCLUDE_FOLDER) $^ -o $@

install:
	mkdir -p $(OUTPUT_FOLDER)

clean:
	rm -rf $(OUTPUT_FOLDER)/*

.PHONY: all clean install